"""Configuration management for dogood."""

import json
import os
import subprocess
from pathlib import Path
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(PROJECT_ROOT / ".env", override=True)


def _get_gh_token() -> str:
    """Get GitHub token from env or gh CLI."""
    token = os.getenv("GITHUB_TOKEN", "")
    if token:
        return token
    try:
        result = subprocess.run(
            ["gh", "auth", "token"], capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return ""


# --- GitHub ---
GITHUB_TOKEN = _get_gh_token()
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME", "danielalanbates")
GITHUB_GRAPHQL_URL = "https://api.github.com/graphql"

# --- Paths ---
DATA_DIR = PROJECT_ROOT / "data"
DB_PATH = DATA_DIR / "github_helper.db"  # Legacy name kept for backward compatibility
WORK_DIR = Path(os.getenv("WORK_DIR", "/tmp/dogood-workdir"))
SEED_DATA_PATH = PROJECT_ROOT / "awesome-for-beginners" / "data.json"

# --- Rate Limiting ---
SEARCH_DELAY_SECONDS = 2.5  # ~24 searches/min (safe under 30/min limit)

# --- Scoring Weights ---
WEIGHT_POPULARITY = 0.20
WEIGHT_SOCIAL_IMPACT = 0.30
WEIGHT_NEED = 0.25
WEIGHT_KINDNESS = 0.25

# --- Social Impact Topics ---
SOCIAL_TOPICS = {
    "nonprofit", "charity", "social-impact", "tech-for-good",
    "accessibility", "a11y", "education", "edtech", "health",
    "healthcare", "climate", "sustainability", "environment",
    "open-data", "civic-tech", "humanitarian", "disaster-relief",
    "food-security", "clean-water", "poverty", "human-rights",
    "mental-health", "assistive-technology",
}

# --- Bounty labels (top priority, always use opus) ---
BOUNTY_LABELS = {
    "bounty", "reward", "paid", "cash", "💰", "💵",
    "has bounty", "has-bounty", "bounty-posted",
}

# --- Labels reserved for human beginners (we skip these) ---
BEGINNER_LABELS = {
    "good first issue", "good-first-issue", "beginner",
    "easy", "first-timers-only", "starter", "low-hanging-fruit",
    "up-for-grabs",
}

# --- Non-actionable labels (skip — these aren't real bugs to fix) ---
SKIP_LABELS = {
    "discussion", "question", "wontfix", "won't fix", "wont-fix",
    "duplicate", "invalid", "by design", "not a bug", "not-a-bug",
    "stale", "needs more info", "needs-more-info", "needs-reproduction",
    "waiting for response", "waiting-for-response", "blocked",
    "proposal", "rfc", "meta", "epic",
}

# --- Ethics Filter ---
# Repos/topics we refuse to contribute to. We only help build things that
# are wholesome and align with Christian values.
BLOCKED_TOPICS = {
    "nsfw", "adult", "porn", "pornography", "sex", "erotic", "hentai",
    "xxx", "nudity", "onlyfans", "cam", "escort", "fetish", "strip",
    "gambling", "casino", "betting", "slot-machine",
    "drugs", "drug-market", "darknet-market",
    "weapon", "exploit-kit", "malware", "ransomware", "spyware",
    "occult", "satanism", "witchcraft",
}
BLOCKED_DESCRIPTION_KEYWORDS = {
    "pornograph", "adult content", "nsfw", "erotic", "sex toy",
    "gambling platform", "casino", "betting platform",
    "drug market", "darknet", "exploit kit", "malware",
}

# --- Anti-AI Policy Detection ---
# Keywords in CONTRIBUTING.md / README.md that indicate AI contributions are banned.
ANTI_AI_KEYWORDS = {
    "no ai", "no llm", "ai-generated", "ban ai", "no bots",
    "ai contributions not accepted", "ai-free", "no machine",
    "ai-generated contributions", "do not use ai", "don't use ai",
    "generated by ai", "written by ai", "no copilot",
    "no chatgpt", "no claude", "llm-generated",
}

# --- Manually Blocked Orgs/Repos ---
# Repos or orgs that silently closed/locked our PRs (anti-AI policy not documented).
BLOCKED_ORGS = {
    "mrdoob",  # three.js — closes and locks AI PRs without comment
    "ChatGPTNextWeb",  # NextChat — silently closes all PRs
}
BLOCKED_REPOS = {
    "LibreTranslate/LibreTranslate",  # silently closes PRs
}

# --- Supported Languages ---
# We only fix bugs in repos whose primary language is one of these.
SUPPORTED_LANGUAGES = {
    "Python", "JavaScript", "TypeScript", "Shell", "Bash",
    "YAML", "SQL", "HTML", "CSS", "Nunjucks", "EJS", "Astro",
    "Vue", "Svelte", "SCSS", "Less", "Markdown", "Lua",
}

# File extensions we can work with (mapped from SUPPORTED_LANGUAGES)
SUPPORTED_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    ".sh", ".bash", ".zsh",
    ".yaml", ".yml", ".sql", ".lua",
    ".html", ".htm", ".css", ".scss", ".less",
    ".vue", ".svelte", ".astro", ".ejs", ".njk",
    ".md", ".mdx", ".json", ".toml",
}

# File extensions that signal the bug is NOT in our wheelhouse
UNSUPPORTED_EXTENSIONS = {
    ".rs", ".go", ".java", ".kt", ".scala", ".clj",
    ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp",
    ".cs", ".rb", ".php", ".swift", ".m", ".mm",
    ".r", ".R", ".jl", ".hs", ".erl", ".ex", ".exs",
    ".dart", ".pl", ".pm",
}

# --- CLA/DCO Detection ---
# Only catch repos that EXPLICITLY REQUIRE signing a CLA to contribute.
# We want enforcement language ("must sign", "required to sign", "please sign")
# near CLA mentions — NOT informational mentions like "we have a CLA".

# Definite enforcement phrases (substring match, no context needed)
CLA_KEYWORDS = {
    "cla-assistant",              # CLA bot that blocks PRs
    "cla assistant",              # Same bot, different formatting
    "sign the cla",               # Direct instruction to sign
    "sign a cla",                 # Direct instruction to sign
    "sign our cla",               # Direct instruction to sign
    "must sign the contributor",  # "must sign the contributor license agreement"
    "required to sign a contributor", # Enforcement language
    "generative ai agreement",   # AI-specific contributor agreement
    "ai contribution agreement",  # AI-specific contributor agreement
    "ai policy agreement",        # AI policy before contributing
}

# Contextual regex: enforcement language near CLA/contributor agreement
# These catch phrases like "you must sign a CLA before submitting"
CLA_CONTEXTUAL_PATTERNS = [
    # "must/need to/required to/have to/please sign [a/the/our] CLA"
    r'(?:must|need to|required to|have to|please)\s+sign\s+(?:a\s+|the\s+|our\s+)?(?:cla\b|contributor\s+(?:license\s+)?agreement)',
    # "CLA must/needs to/is required to be signed"
    r'\bcla\b\s+(?:must|needs? to|is required to)\s+be\s+signed',
    # "signing (?:a|the|our) CLA is required/mandatory/necessary"
    r'signing\s+(?:a\s+|the\s+|our\s+)?(?:cla\b|contributor\s+(?:license\s+)?agreement)\s+is\s+(?:required|mandatory|necessary)',
    # "submit/accept/complete (?:a|the|our) contributor license agreement"
    r'(?:submit|accept|complete)\s+(?:a\s+|the\s+|our\s+)?contributor\s+license\s+agreement',
    # "PRs require a signed CLA" / "contributions require signing a CLA"
    r'(?:pull requests?|prs?|contributions?)\s+(?:\w+\s+){0,3}require\s+(?:\w+\s+){0,2}(?:sign|cla\b|contributor\s+(?:license\s+)?agreement)',
]

DCO_KEYWORDS = {
    "developer certificate of origin",
    "signed-off-by",
}

# Workflow files that enforce CLA/DCO (these actively block PRs)
CLA_WORKFLOW_FILES = [
    ".github/workflows/cla.yml",
    ".github/workflows/cla.yaml",
]
DCO_WORKFLOW_FILES = [
    ".github/workflows/dco.yml",
    ".github/workflows/dco.yaml",
]

# Org-level CLA blocklist — these orgs require CLAs across all/most repos.
# Populated from confirmed blacklist data (repos that already hit CLA detection).
# Per-repo CONTRIBUTING.md scan still catches any we miss here.
CLA_ORGS = {
    "microsoft", "google", "apache", "dotnet", "tensorflow",
    "facebookresearch", "hashicorp", "Shopify", "Azure", "googleapis",
    "salesforce", "angular", "google-deepmind", "facebookarchive",
    "GoogleChrome", "google-research", "adobe", "grafana",
    "googlecolab", "google-gemini", "googlesamples", "googleworkspace",
    "GoogleCloudPlatform", "eclipse", "SAP", "chef",
    "TransformerOptimus",
    "n8n-io", "Significant-Gravitas", "rabbitmq",
}

# Organizations where we HAVE signed the CLA
SIGNED_CLA_ORGS = {
    "facebook", "meta", "pytorch",  # Meta CLA signed (pytorch uses Meta CLA)
    "google", "google-gemini", "angular", "googleapis",  # Google CLA signed
    "microsoft", "desktop", "dotnet", "azure",  # Microsoft CLA (auto-signs on PR)
    "apache",  # Apache ICLA submitted
}

# --- Factory (inline mode — no subprocesses) ---
MAX_CONCURRENT_AGENTS = 1  # Always 1 — solver runs inline, not as subprocess
AGENT_CLAIM_TTL_MINUTES = 120
MIN_STARS_DEFAULT = 1000  # lowered from 10000
FEEDBACK_POLL_INTERVAL_SECONDS = 300
HOSTILE_SENTIMENT_THRESHOLD = 0.7
MAX_OPUS_PER_ISSUE = 10  # max opus attempts per individual issue before skipping

# --- Quality Gate ---
# Minimum estimated merge probability before a PR is submitted.
# Set to 0.51 to ensure we only submit PRs we expect to get merged >50% of the time.
QUALITY_GATE_THRESHOLD = float(os.getenv("QUALITY_GATE_THRESHOLD", "0.25"))

# --- Anthropic API Rate Limiting ---
# Budget in requests-per-minute across ALL models.
# The factory auto-regulates concurrency to stay under this limit,
# leaving headroom for manual Claude Code sessions.
# Each active agent averages ~10 RPM (30 max_turns over ~3 min).
ANTHROPIC_RPM_BUDGET = int(os.getenv("ANTHROPIC_RPM_BUDGET", "40"))
ESTIMATED_RPM_PER_AGENT = 10  # empirical average per agent

# --- Model Tiers (Daniel Tier System) ---
# Edit tiers.json in the project root to change tiers live — no restart needed.
# The factory hot-reloads this file on each agent spawn.
TIERS_FILE = PROJECT_ROOT / "tiers.json"
ARCHITECT_PREFS_FILE = Path.home() / "Library/Application Support/BatesAI/shared/architect_preferences.json"
SELECTED_MODEL_SIGNAL = Path("/tmp/dogood-selected-provider")
_tiers_cache: dict = {"mtime": 0.0, "architect_mtime": 0.0, "tiers": []}


PRIMARY_MODEL = os.getenv("DOGOOD_PRIMARY_MODEL", "claude-fable-5-1")
# Written by the Do Good Factory menu bar app's AI Models dropdowns.
MODEL_CHOICE_FILE = Path.home() / "Library/Application Support/BatesAI/shared/dogood_models.json"


def _chosen_model(role: str) -> str:
    try:
        model = json.loads(MODEL_CHOICE_FILE.read_text()).get(role)
        if isinstance(model, str) and model.startswith("claude-"):
            return model
    except Exception:
        pass
    return PRIMARY_MODEL


def primary_model() -> str:
    return _chosen_model("primary")


def reviewer_model() -> str:
    return _chosen_model("reviewer")
# A PR is only posted when the independent acceptance review scores at least this.
AUTO_SUBMIT_MIN_CONFIDENCE = float(os.getenv("AUTO_SUBMIT_MIN_CONFIDENCE", "0.95"))


def load_model_tiers() -> list[dict]:
    """Load model tiers. Fable 5.1 is the sole primary driver (Daniel, 2026-09-12)."""
    return [
        {"tier": 1, "model": primary_model(), "effort": "high", "thinking": True, "label": "fable-high"},
    ]


# Initial load — but consumers should call load_model_tiers() for fresh data
MODEL_TIERS = load_model_tiers()

# --- Log file ---
LOG_FILE = PROJECT_ROOT / "Claude Agent - dogood.md"

# --- Human Approval Gate ---
# When true (default), daemons prepare fixes locally and queue the PR in
# PENDING_PR_QUEUE instead of pushing branches or opening pull requests.
# To approve later: review data/pending_prs.jsonl and run the recorded
# push_cmd + pr_create_cmd, or set REQUIRE_HUMAN_APPROVAL=false in .env.
REQUIRE_HUMAN_APPROVAL = os.getenv("REQUIRE_HUMAN_APPROVAL", "true").strip().lower() not in ("0", "false", "no", "off")
PENDING_PR_QUEUE = DATA_DIR / "pending_prs.jsonl"
